config/routes.rb
MoleValley::Application.routes.draw do

  resources :organisations

  resources :events

  resources :comments

  devise_for :users

root :to => 'mole_core#home'

  get "mole_core/home"

  get "mole_core/resources"

  get "mole_core/about"

  get "mole_core/contact"

  get "mole_core/birds"

  get "mole_core/butterflies"

  get "mole_core/fungi"

  get "mole_core/plants"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/organisation.rb
class Organisation < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/mole_core_controller.rb
class MoleCoreController < ApplicationController
  def home
  end

  def resources
  end

  #def organisations
  #end

  def about
  end

  #def events
  #end

  def contact
  end

  def birds
  end

  def butterflies
  end

  def fungi
  end

  def plants
  end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  # GET /organisations
  # GET /organisations.json
  def index
    @organisations = Organisation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organisations }
    end
  end

  # GET /organisations/1
  # GET /organisations/1.json
  def show
    @organisation = Organisation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organisation }
    end
  end

  # GET /organisations/new
  # GET /organisations/new.json
  def new
    @organisation = Organisation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organisation }
    end
  end

  # GET /organisations/1/edit
  def edit
    @organisation = Organisation.find(params[:id])
  end

  # POST /organisations
  # POST /organisations.json
  def create
    @organisation = Organisation.new(params[:organisation])

    respond_to do |format|
      if @organisation.save
        format.html { redirect_to @organisation, notice: 'Organisation was successfully created.' }
        format.json { render json: @organisation, status: :created, location: @organisation }
      else
        format.html { render action: "new" }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organisations/1
  # PUT /organisations/1.json
  def update
    @organisation = Organisation.find(params[:id])

    respond_to do |format|
      if @organisation.update_attributes(params[:organisation])
        format.html { redirect_to @organisation, notice: 'Organisation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organisations/1
  # DELETE /organisations/1.json
  def destroy
    @organisation = Organisation.find(params[:id])
    @organisation.destroy

    respond_to do |format|
      format.html { redirect_to organisations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/mole_core_helper.rb
module MoleCoreHelper
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_id %><br />
    <%= f.number_field :event_id %>
  </div>
  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_area :details %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Event</th>
    <th>Details</th>
    <th>Author</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.event_id %></td>
    <td><%= comment.details %></td>
    <td><%= comment.author %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Event:</b>
  <%= @comment.event_id %>
</p>

<p>
  <b>Details:</b>
  <%= @comment.details %>
</p>

<p>
  <b>Author:</b>
  <%= @comment.author %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<article>
  <h1>Natural History Related Events in Mole Valley</h1>
  <p>
    <%= image_tag "butterflies/Adonis-Blue-face.jpg", :class => 'butterfliesLeft',
                    :title => 'Adonis Blue face on. Copyright: Jeremy Early', :alt => "Adonis Blue butterfly face on" %>
  </p>
  <p>
    Mole Valley has a lively and active community of natural history enthusiasts. There are events
    that suite all levels of experience. We provide here some links that will keep you up to date
    with natural history related activities in Mole Valley.
  </p>
  <p>
    The RSPB Dorking and District Local Group organise regular events throughout the year that are
    open to all. You do not need to be an expert birdwatcher. Indeed you will find many are ideal
    for those that are wanting to get started. An up to date programme of events can be found
    <%= link_to("here", "http://www.rspb.org.uk/groups/dorkinganddistrict/events/", {:target => "_blank"}) %>.
  </p>
  <section class="clearfix">
  <%= image_tag "Adders-dancing.jpg", :class => 'butterfliesRight',
                    :title => 'Male Adders dancing. Copyright: Jeremy Early', :alt => "Male Adders dancing" %>
  <p>
    Amphibians and Reptiles are important indicators of habitat quality. The Surrey Amphibian and Reptile
    Group is an extremely active and enthusiastic group that provides important support for some of our
    most threatened habitats. An up to date list of their events can be found
    <%= link_to("here", "http://surrey-arg.org.uk/SARG/30000-CommitteeTools/calendar/SARGcalendar.asp", {:target => "_blank"}) %>.
  </p>
  </section>
</article>

<h1>Listing events</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Date</th>
    <th>Description</th>

    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.title %></td>
    <td><%= event.date %></td>
    <td><%= event.description %></td>
    <td><%= link_to 'Show', event %></td>

    <% if user_signed_in? %>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, confirm: 'Are you sure?', method: :delete %></td>
  <% end %>
  </tr>
 <% end %>
</table>

<br />
 <% if user_signed_in? %>
<%= link_to 'New Event', new_event_path %>
<%end%>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @event.title %>
</p>

<p>
  <b>Date:</b>
  <%= @event.date %>
</p>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/_footer.html.erb
<footer id="page_footer" role="footer">
  &copy; <%= Time.now.year %> Mole Valley Natural History
</footer>

app/views/layouts/_header.html.erb
<html>
<header id= "page_header" role= "banner">

<%= image_tag "banner.png", :class => 'main-image', :height=>'100', :width=>'1000' %>

 <!-- -->


</header>
</html>

app/views/layouts/_navigation.html.erb
<nav id="main_nav" role="navigation">
  <ul>
    <li><%= link_to "Home",  "/mole_core/home" %></li>
    <li><%= link_to "Organisations", "/organisations"%></li>
    <li><%= link_to "What is here?", "/mole_core/about" %></li>
    <li><%= link_to "Events", "/events"%></li>
    <li><%= link_to "Contact us", "/mole_core/contact"%></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset = "utf-8">

  <title>MoleValley</title>
  <%= stylesheet_link_tag    "application" , :media => "all"%>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


<div id= "container">
	<%= render 'layouts/header' %>
	

		<section id='flash_messages'>
  		<p class="notice"><%=notice%></p>
  		<p class="alert"><%=alert%></p>

  		<%= render 'layouts/navigation' %>

  		<section class="sidebar" id="right">
		<% if user_signed_in? %>
		    Signed in as <%= current_user.email %>: 
		    <%= link_to "Sign out", destroy_user_session_path,:method => :delete %>
		<% else %>
		    <%= link_to "Sign up", new_user_registration_path %> or 
            <%= link_to "Sign in", new_user_session_path %>
		<% end %>
	</section>



<%= yield %>



<%=render 'layouts/footer'%>

  </section>
		
		


</div>


</body>
</html>

app/views/mole_core/about.html.erb
<article>
  <h1>What you can see</h1>
  <%= image_tag "Mute_Swan_heads.jpg", :class => 'main-image', :alt => "Mute Swans" %>
  <p>
    You can find here links to information on a range of characteristic species
    that are found in Mole Valley.
  </p>

<h2><%= link_to "Birds", "/mole_core/birds" %></h2>

<h2>Bats</h2>

<h2><%= link_to "Butterflies", "/mole_core/butterflies" %></h2>

 <p>
    About 60 different kinds of butterfly occur in Britain. More than half of them can be
    seen in Mole Valley, including several nationally scarce butterflies of chalk
    grassland and woodland. The high number of species found locally reflects the location of Mole
    Valley in the warm south east corner of England, and the variety of habitats.
    Fewer species can survive in the north of Britain, although some are moving
    northwards as a result of climate change.
  </p>

  <h2>Dragonflies and Damselflies</h2>

<h2><%= link_to "Fungi", "/mole_core/fungi" %></h2>

<h2>Moths</h2>

<h2><%= link_to "Plants", "/mole_core/plants" %></h2>

</article>

app/views/mole_core/birds.html.erb
<article>
  <section class="taxon">
    <p>
      Mole Valley is home to a wide range of bird species, many of which favour
      particular habitats. Some of these are highlighted below:
    </p>
  </section>

  <section class="taxon">
    <h2>River Mole</h2>
    <p>
      <%= image_tag "birds/Kingfisher with fish.jpg", :class => 'birds',
                    :title => 'Kingfisher with fish. Copyright: Jeremy Early', :alt => "Kingfisher with fish" %>
      Kingfishers can be seen along the length of the river – a flash of blue and
      orange flying swiftly past. Grey wagtails are also common often seen around
      the Leatherhead Town Bridge and in Winter goosanders can be seen swimming
      along the river.
    </p>
  </section>

  <section class="taxon">
    <h2>Ponds and streams</h2>
    <p>
      <%= image_tag "birds/Grey_Wagtail.jpg", :class => 'birds',
                    :title => 'Grey Wagtail. Copyright: Jeremy Early', :alt => "Grey Wagtail" %>
      Many common birds can be seen on our ponds and streams including mallards,
      coots, moorhens, Canada geese, greylag geese and grey wagtails.
    </p>
  </section>

  <section class="taxon">
    <h2>Farmland</h2>
    <%= image_tag "birds/red legged partridge.jpg", :class => 'birds',
                  :title => 'Red-legged Partridge. Copyright: Heather & Don Gerrard', :alt => "Red-legged Partridge" %>
    <p>
      There is a range of birds found in our farmland habitat including game birds
      such as pheasants and red-legged partridge. In the hedgerows you can see
      yellowhammers and finches and feeding in the fields there are often skylarks
      and thrushes; in the Winter the song and mistle thrushes are joined by
      redwings and fieldfares from Scandinavia.
    </p>
  </section>

  <section class="taxon">
    <h2>Woodland</h2>
    <p>
      <%= image_tag "birds/lesser redpoll.jpg", :class => 'birds',
                    :title => 'Lesser Redpoll. Copyright: Heather & Don Gerrard', :alt => "Lesser Redpoll" %>
      Our woodland areas host a wide variety of birds including 5 species of tit
      (blue, great, coal, long-tailed and marsh), great spotted woodpeckers,
      redpolls and siskins.
    </p>
  </section>

  <section class="taxon">
    <h2>Urban parks, green spaces and gardens</h2>
    <p>
      <%= image_tag "birds/House-Martin.jpg", :class => 'birds',
                    :title => 'House Martin collecting nesting material. Copyright: Jeremy Early', :alt => "House Martin" %>
      Another rich environment for several species of birds which include:
      green woodpeckers, robins, blackbirds, tits, pied wagtails and many more.
    </p>
  </section>

  <section class="taxon">
    <h2>Commons and Heaths</h2>
    <p>
      <%= image_tag "birds/Nightingale.jpg", :class => 'birds',
                    :title => 'Nightingale. Copyright: Jeremy Early', :alt => "Nightingale" %>
      Our commons and heathlands are home all year round to birds such as finches
      and tits. Rarer summer migrants include woodlarks (Headley Heath),
      nightingales and warblers (Bookham Common). Arguably the most important
      bird site in Mole Valley is Bookham Common for nightingales.
    </p>
  </section>
</article>

app/views/mole_core/contact.html.erb
<article>
  <h1>Contact Us</h1>
  <%= image_tag "Denbies-Hillside.jpg", :class => "birdsCentre", :title => 'Denbies Hillside. Copyright: Jeremy Early', :alt => "Denbies Hillside near Dorking" %>
  <p>
    We are always looking for additional support. A contact point is currently being arranged (February 2012)
    and will be added as soon as possible. Do get in touch if you would either like to offer help or
    if you would like some advice on nature conservation in Mole Valley.
  </p>
  <p>
    N.B. This page is currently being revised and an updated version will be provided shortly.
  </p>
</article>

app/views/organisations/_form.html.erb
<%= form_for(@organisation) do |f| %>
  <% if @organisation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organisation.errors.count, "error") %> prohibited this organisation from being saved:</h2>

      <ul>
      <% @organisation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organisations/edit.html.erb
<h1>Editing organisation</h1>

<%= render 'form' %>

<%= link_to 'Show', @organisation %> |
<%= link_to 'Back', organisations_path %>

app/views/organisations/index.html.erb
<h1>Listing organisations</h1>

  <p>
    <a href="http://www.surreyflora.org.uk" target="outside_link">Surrey Botanical Society</a><br>

    <summary>
     Originally known as Surrey Flora Committee, our Surrey Botanical Society has been well-established for many years, to represent and unite all those who want to enjoy, study, and record Surrey's astonishingly interesting, beautiful, and diverse flora.
    </summary>
  </p>

  <p>
    <a href="http://www.surreycc.gov.uk/sccwebsite/sccwspages.nsf/LookupWebPagesByTITLE_RTF/Lower+Mole+project?open%20document" target="outside_link">Lower Mole Countryside Project</a><br>

     <summary>
      The Lower Mole Project is a partnership with boroughs, districts and other organisations.
      The Lower Mole Countryside Management Project has been in existence since 1983 and was the first Project to be established in the north Surrey area. It has built up a large and enthusiastic volunteer group which carries out a wide range of tasks to implement improvements to the local countryside, 4 days a week, including weekends, throughout the year.
    </summary>
  </p>

  <p>
    <a href="http://www.nationaltrust.org.uk/main/w-global/w-localtoyou/w-south_east/w-south_east-contact_us.htm" target="outside_link">National Trust</a><br>
     <summary>
     We protect historic houses, gardens, mills, coastline, forests, woods, fens, beaches, farmland, moorland, islands, archaeological remains, nature reserves, villages and pubs. Then we open them up for ever, for everyone.
     </summary>
     <details>
    Many people don't know that we were founded over 100 years ago, by three passionate Victorians who wanted to preserve outdoor spaces and prevent them from being built on. Find out more about where we've come from and the extraordinary, Octavia Hill, the visionary behind our organisation.
    </details>
    </p>

  <p>
    <a href="http://www.surreywildlifetrust.co.uk/" target="outside_link">Surrey Wildlife Trust</a><br>
  <summary>
    Surrey Wildlife Trust (SWT) is a registered charity and the only organisation concerned solely with the conservation of all forms of wildlife in Surrey. 
  </summary>
   <details>
  We care for more than 9,000 hectares of the county’s countryside for the benefit of people and wildlife. We are the largest Wildlife Trust in terms of land managed - being responsible for 4.5% of the county. SWT is part of a nationwide network of 47 local Trusts working to protect wildlife in towns and the countryside. Collectively, the Wildlife Trusts have 800,000 members and thousands of nature reserves.
   </details>
  </p>

 <p>
    <a href="http://surrey-arg.org.uk/" target="outside_link">Surrey Amphibian and Reptile Group</a><br>
  <summary>
  The Surrey amphibian and reptile group is a non-profit-making wildlife conservation organisation, based in the United Kingdom's county of Surrey. 
  </summary>
  <details>
  SARG focuses on the care and preservation of wild, native reptiles and amphibians.
  SARG was established in 1987 by people with an interest in Surrey's reptiles and amphibians. Surrey is very fortunate in being home to all of the UK's native species of reptiles and amphibians, including the very rare Smooth Snake and Great Crested Newt, and we want to see these creatures thrive in the County.
  We are a mixture of hobbyists, scientists, and conservationists; amateurs and professionals, committed to sharing knowledge and understanding of these much-misunderstood and endangered animals.
  We are affiliated to Surrey Wildlife Trust, and form part of the national ARG-UK network. We work voluntarily to prevent habitat destruction and resist damaging planning applications. We give advice to residents and organisations, work with schools and educational bodies, and help with numerous "toad-crossing" sites throughout Surrey.
</details> 
  </p>

   <p>
    <a href="http://www.butterfly-conservation.org/" target="outside_link">Butterfly Conservation</a><br>
  <summary>
  Butterfly Conservation has raised awareness of the drastic decline in butterflies and moths, and created widespread acceptance that action needs to be taken.
  We recently published a butterfly report showing that three-quarters of butterflies in the UK have declined and over 45% are threatened.
  </summary>
  </p>
  
   <p>
    <a href="http://www.molevalley.gov.uk/" target="outside_link">Mole Valley District Council</a><br>
  <summary>
    Mole Valley lies at the heart of Surrey, mid-way between London and the Sussex coast. It has a population of approximately 83,800 people. The majority of the district's population (72%) live in the main towns and villages of the district, in particular, Dorking and Leatherhead.
  </summary>
  </p>
  
  <p>
    <a href="http://www.rspb.org.uk/groups/dorkinganddistrict" target="outside_link">RSPB Dorking and District Local Group</a><br>Leatherhead and District Countryside Protection Society<br>
     <summary>
      The Group covers a large area of mid-Surrey but centered on Dorking, Leatherhead and The Bookhams. During the winter indoor meetings are held once a month. Bird-watching walks and related activities are organised at the weekends and mid-week: a coach is usually arranged for the more remote destinations. Most of the walks are fairly easy. New members are always welcome and a special effort is made for those who are beginners.
    </summary>
    </p>
   
   <p>
    <a href="http://www.britmycolsoc.org.uk/" target="outside_link">British Mycological Society</a><br>
  <summary>
    The British Mycological Society is a registered British Charity open to all who are interested in promoting and learning about the exciting world of fungi. 
  </summary>
  <details>
    It has member sections devoted to particular aspects of the fungal world including cutting edge research into many aspects of fungal science, the conservation and recording of fungi and the provision of educational resources for use at all ages and experience. If you are working with, fascinated by or wish to learn about fungi the Society can help.
  </details> 
  </p>

  
<h1>More organisations</h1>
<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @organisations.each do |organisation| %>
  <tr>
    <td><%= organisation.name %></td>
    <td><%= link_to 'Show', organisation %></td>
    <td><%= link_to 'Edit', edit_organisation_path(organisation) %></td>
    <td><%= link_to 'Destroy', organisation, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Organisation', new_organisation_path %>

app/views/organisations/new.html.erb
<h1>New organisation</h1>

<%= render 'form' %>

<%= link_to 'Back', organisations_path %>

app/views/organisations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @organisation.name %>
</p>


<%= link_to 'Edit', edit_organisation_path(@organisation) %> |
<%= link_to 'Back', organisations_path %>